version: '3.4'

services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data

  redis:
    container_name: redis-brain-agriculture
    image: redis:alpine
    ports:
      - 6379:6379
volumes:
  db:
    driver: local